apiVersion: v1
kind: Service
metadata:
  name: nagios-service
  labels:
    app: nagios
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nagios

